FROM ubuntu:bionic

# IMAGE INFORMATION
LABEL maintainer="nagatax<4foview@gmail.com>" \
    title="baseos" \
    version="ubuntu" \
    description="This image is base image"
 
# COMMON SETTING
ENV SRC_DIR="/usr/local/src" \
    INSTALL_DIR="/usr/local" \
    BUILD_DIR="/usr/local/build"

# Change executable user
USER root

RUN set -x; \
    apt update -y \
    && apt upgrade -y

# Set a command when system will start
CMD ["/bin/bash"]
