#!/bin/bash

##################################################
# Dockerイメージを登録する
#
# Environment Variables
#  PACKAGE: package name
#  PACKAGE_VERSION: package version
#  PACKAGE_LATEST: latest version of package
#  D_IMAGE: image name of Docker
#  DH_IMAGE: image name of Docker Hub
#  DH_LATEST: latest image name of Docker Hub
#
# Precondition
#  Need to set DH_USER and DH_PASSWD.
##################################################

# Set shell option
set -eu

# Load some environmental values
source ./apache/hooks/env.sh

# Register in Docker Hub
source ./apache/../lib/dockerhub.sh
pushImage ${DH_USER} ${DH_PASSWD} ${D_IMAGE} ${PACKAGE} ${PACKAGE_VERSION} ${PACKAGE_LATEST}

# Register tag in Git Hub
# echo "Pushing git tag"
# git tag -d "${PACKAGE}-v${PACKAGE_VERSION}"
# git push origin :"${PACKAGE}-v${PACKAGE_VERSION}"
# git tag -a "${PACKAGE}-v${PACKAGE_VERSION}" -m "${PACKAGE} version ${PACKAGE_VERSION}"
# git push origin "${PACKAGE}-v${PACKAGE_VERSION}"