#!/bin/bash
set -eu

# ビルドイメージの作成
echo "image for building"
docker image build -t ${IMAGE_NAME} . -f Dockerfile.build

# デプロイファイルをローカルにコピー
mkdir -p deploy_files
docker container create --name extract ${IMAGE_NAME}
docker container cp extract:/usr/local/pcre deploy_files
docker container cp extract:/usr/local/nginx deploy_files
docker container cp extract:/root/.bashrc deploy_files
docker container rm extract
docker image rm ${IMAGE_NAME}

# リリースイメージの作成
echo "Building image for release"
docker image build --no-cache -t ${IMAGE_NAME} .

# ローカルのデプロイファイルを削除
rm -rf deploy_files
