#!/bin/sh

##################################################
# Dockerイメージを作成する
##################################################

# Load some environmental values
source ./nginx/hooks/env.sh

# Building a docker image
echo "Building a docker image"
docker image build . --build-arg NGINX=${PACKAGE} --build-arg NGINX_VERSION=${PACKAGE_VERSION} -t ${D_IMAGE} -f ./nginx/Dockerfile
