#!/bin/bash
set -eu

echo "image for building"

# dockerイメージのビルド
docker build -t ${IMAGE_NAME} . -f Dockerfile.build

mkdir -p deploy_files/gcc-7.4.0
docker container create --name extract ${IMAGE_NAME}
docker container cp extract:/usr/local/gcc deploy_files
docker container cp extract:/root/.bashrc deploy_files
docker container rm -f extract
docker rmi ${IMAGE_NAME}

echo "Building image for release"

docker build --no-cache -t ${IMAGE_NAME} .

rm -rf deploy_files
