#!/bin/bash
set -eu

echo "image for building"

# 実行環境の設定
#  true:試験環境
#  false:本番環境
IS_DEVELOPMENT="false"

# dockerイメージのビルド
docker build --build-arg IS_DEVELOPMENT=${IS_DEVELOPMENT} \
    -t ${IMAGE_NAME} . -f Dockerfile.build

mkdir -p deploy_files/gcc-7.4.0
docker container create --name extract ${IMAGE_NAME}
docker container cp extract:/usr/local/gcc-7.4.0 deploy_files
docker container cp extract:/root/.bashrc deploy_files
docker container rm -f extract
docker rmi ${IMAGE_NAME}

echo "Building image for release"

docker build --no-cache \
    -t ${IMAGE_NAME} .

rm -rf deploy_files
