#!/bin/bash

##################################################
# Create base image
#
# Precondition
#  Need to set DH_USER and DH_PASSWD.
##################################################

# Set shell option
set -eu

# CentOS

## Building docker image
echo "Building docker image"
docker image build . -t ${DH_USER}/base_os:centos_7 -f Dockerfile.centos

# Ubuntu

## Building docker image
echo "Building docker image"
docker image build . -t ${DH_USER}/base_os:ubuntu_bionic -f Dockerfile.ubuntu

## Push docker image
echo "Pushing docker image"
docker login -u ${DH_USER} -p ${DH_PASSWD}
docker image push ${DH_USER}/base_os:centos_7
docker image push ${DH_USER}/base_os:ubuntu_bionic
docker logout