#!/bin/sh

##################################################
# Dockerイメージを作成する
##################################################

# Load some environmental values
source ./redis/hooks/env.sh

# Building a docker image
echo "Building a docker image"
docker image build . --build-arg REDIS=${PACKAGE} --build-arg REDIS_VERSION=${PACKAGE_VERSION} -t ${D_IMAGE} -f ./redis/Dockerfile