#!/bin/bash
set -eu

# 環境変数の設定
if [ -z "${IMAGE_NAME}" ]; then
  export IMAGE_NAME="redis:build"
fi
if [ -z "${DOCKER_REPO}" ]; then
  export DOCKER_REPO="redis"
fi
if [ -z "${CACHE_TAG}" ]; then
  export CACHE_TAG="build"
fi
